import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Luminal Frontier Design System Colors
        primary: "#a8e8ff",
        "primary-container": "#00d4ff",
        secondary: "#d9b9ff",
        "secondary-container": "#8c0eff",
        background: "#0a0a0f",
        surface: "#131318",
        "surface-container-lowest": "#0e0e13",
        "surface-container-low": "#1b1b20",
        "surface-container": "#1f1f25",
        "surface-container-high": "#2a292f",
        "surface-container-highest": "#35343a",
        "surface-bright": "#39383e",
        "surface-variant": "#35343a",
        "on-primary": "#003642",
        "on-primary-container": "#00586b",
        "on-surface": "#e4e1e9",
        "on-surface-variant": "#bbc9cf",
        "on-background": "#e4e1e9",
        outline: "#859398",
        "outline-variant": "#3c494e",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "tertiary-container": "#c2c3c3",
        inverse: "#131318",
        "inverse-surface": "#e4e1e9",
        "inverse-on-surface": "#303036",
        "inverse-primary": "#00677e",
        "surface-tint": "#3cd7ff",
        "primary-fixed": "#b4ebff",
        "primary-fixed-dim": "#3cd7ff",
        "on-primary-fixed": "#001f27",
        "on-primary-fixed-variant": "#004e5f",
        "secondary-fixed": "#eedbff",
        "secondary-fixed-dim": "#d9b9ff",
        "on-secondary": "#460085",
        "on-secondary-fixed": "#2a0054",
        "on-secondary-fixed-variant": "#6400ba",
        "on-secondary-container": "#efdeff",
        tertiary: "#dedfdf",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary": "#2f3131",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary-container": "#4f5051",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
